server:
  port: 10010
spring:
  application:
    name: ptCMSConfig
  profiles:
    #使用本地配置存储
    active: native
  cloud:
    config:
      server:
#本地配置
        native:
          search-locations:
          - classpath:/config_repo
#远端git配置
#      kabel: master #分支
#        git:
#          uri: https://github.com/cralor7/springcloud
#          search-paths: config-repo
          #username:
          #password:
#          default-label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/

